### ISSUE TITLE
Getting NetworkError while configuring packtag with IBM wcs

### ISSUE THREAD

**Issue by inigoarulraj** [galan/packtag#9]
While configuring  packtag with IBM wcs. I am getting the following error in firbug console.
NetworkError: 500 Internal Server Error - http:/hostname/webapp/wcs/stores/external.js.h1759258844.pack

**Comment by galan** [comment]
Hi, I'm sorry, but from the short error description I can't deduce the error. However I remember that there were some issues regarding pack:tag with WebSphere. Since I'm not actively maintaining this project, you might dig into the issue by debugging the code and maybe you could create an pull request that I might merge.
